---
language: node_js
node_js:
  - "10"

branches:
  except:
    - /^dependabot\/.*$/

addons:
  chrome: stable

cache:
  yarn: true

install:
  - yarn install --no-lockfile

script:
  - yarn lint
  - yarn test
