name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
    tags:
      - "v*"
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "10"

      - run: yarn install
      - run: yarn lint
      - run: yarn test --coverage

  compatibility:
    name: "Ember Compat: ember-qunit: ${{ matrix.ember-qunit-version }} | Embroider: ${{ matrix.embroider }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ember-qunit-version: [4, 5]
        embroider: ["false"]
        include:
          # embroider + ember-qunit v5 is disabled for now until it actually works...
          - ember-qunit-version: 4
            embroider: "true"


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 10

      - run: yarn install --frozen-lockfile
      - run: yarn ember try:one --config-path tests/dummy/config/ember-try.js ember-qunit-${{ matrix.ember-qunit-version }}
        env:
          QUNIT_CONSOLE_GROUPER: "true"
          USE_EMBROIDER: "${{ matrix.embroider }}"

  release:
    name: Release
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
